name: Release

on:
  release:
    types: [ released ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.3.1"
      - name: Poetry install
        run: poetry install --all-extras
      - name: Publish
        run: |
          poetry publish \
            --build \
            --username __token__ \
            --password "${{ secrets.PYPI_TOKEN }}"
